# Fish completion for clawsec
complete -c clawsec -s l -d 'Listen mode for inbound connections'
complete -c clawsec -s p -x -d 'Local port number'
complete -c clawsec -s k -x -d 'Encryption password (required)'
complete -c clawsec -s u -d 'UDP mode (default: TCP)'
complete -c clawsec -s 4 -d 'Force IPv4 only'
complete -c clawsec -s 6 -d 'Force IPv6 only'
complete -c clawsec -s c -d 'Chat mode with timestamps and colors'
complete -c clawsec -s v -d 'Verbose output'
complete -c clawsec -s w -x -d 'Connection timeout in seconds'
complete -c clawsec -s e -r -F -d 'Execute program after connect'
complete -c clawsec -s z -d 'Compress data with zlib before encryption'
complete -c clawsec -s P -d 'Show transfer progress bar'
complete -c clawsec -s V -d 'SHA-256 end-to-end file verification'
complete -c clawsec -s n -x -d 'Chat nickname'
complete -c clawsec -s K -d 'Keep-open: accept multiple clients'
complete -c clawsec -s L -x -d 'Port forwarding target (host:port)'
complete -c clawsec -l obfs -x -a 'http tls' -d 'Traffic obfuscation mode'
complete -c clawsec -l pad -d 'Pad all packets to uniform 1400 bytes'
complete -c clawsec -l jitter -x -d 'Random delay between packets (ms)'
complete -c clawsec -l ech -d 'Encrypted Client Hello (hide SNI from DPI)'
complete -c clawsec -l mux -d 'Multiplex streams over one encrypted tunnel'
complete -c clawsec -l fallback -x -d 'Proxy non-ClawSec probes to real site (host:port)'
complete -c clawsec -l fingerprint -x -a 'chrome firefox safari' -d 'Mimic browser TLS fingerprint'
complete -c clawsec -l tofu -d 'Trust On First Use (SSH-like server identity)'
complete -c clawsec -l pq -d 'Post-quantum hybrid (X25519 + ML-KEM-768)'
complete -c clawsec -l tun -x -d 'TUN VPN mode (ip/mask)'
complete -c clawsec -l tun-udp -d 'UDP data channel for VPN'
complete -c clawsec -l masquerade -d 'Enable NAT/masquerade on VPN server'
complete -c clawsec -l default-route -d 'Route all traffic through VPN tunnel'
complete -c clawsec -l scan -x -d 'Port scanner (range: 1-1024, 80, all)'
complete -c clawsec -s b -d 'Banner grabbing during port scan'
complete -c clawsec -l socks -x -d 'SOCKS5 proxy through encrypted tunnel (port)'
complete -c clawsec -l send -r -F -d 'Send file through encrypted tunnel'
complete -c clawsec -l recv -r -d 'Receive file into directory'
complete -c clawsec -s R -x -d 'Reverse tunnel (host:port)'
complete -c clawsec -l persistent -d 'Auto-reconnect with exponential backoff'
complete -c clawsec -s h -d 'Display usage information'
